-- TABEL GALLERY --
CREATE TABLE IF NOT EXISTS gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT NOT NULL,
    alt_text TEXT,
    display_order INTEGER DEFAULT 99,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- RLS POLICIES (Keamanan) --
ALTER TABLE gallery ENABLE ROW LEVEL SECURITY;

-- Semua orang bisa melihat (SELECT)
CREATE POLICY "Public Gallery Access" ON gallery
    FOR SELECT USING (true);

-- Hanya Admin/Authenticated user yang bisa menambah (INSERT)
CREATE POLICY "Admin Insert Gallery" ON gallery
    FOR INSERT TO authenticated WITH CHECK (true);

-- Hanya Admin/Authenticated user yang bisa mengubah/menghapus (UPDATE/DELETE)
CREATE POLICY "Admin Delete Gallery" ON gallery
    FOR DELETE TO authenticated USING (true);
